# Makefile: A standard Makefile for main.cpp

CC       = g++
LD       = $(CC)
CPPFLAGS =-g -std=c++20 -Wall -Werror -Wpedantic -Wno-parentheses
#LDFLAGS  = -lstdc++

all  : main
main : main.o
clean:
	/bin/rm -rf main main.o
# END OF FILE
